name: Build Bot App

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Add Garage Group NuGet Source
      run: >
        dotnet nuget add source ${{ vars.GG_NUGET_SOURCE_URL }}
        -n garage
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-restore -c Release

  ping-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v3
      with:
        url: https://${{ vars.TEST_WEBAPP_NAME }}.azurewebsites.net/api/health?code=${{ secrets.TEST_BOTFUNC_KEY }}
        follow-redirect: false
        max-attempts: 3
        retry-delay: 5s
        retry-all: false

  ping-prod:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v3
      with:
        url: https://${{ vars.PROD_WEBAPP_NAME }}.azurewebsites.net/api/health?code=${{ secrets.PROD_BOTFUNC_KEY }}
        follow-redirect: false
        max-attempts: 3
        retry-delay: 5s
        retry-all: false